# Generated by Django 3.1.4 on 2020-12-31 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='catalog_id',
            new_name='catalog',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
