# Generated by Django 3.1.4 on 2020-12-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_catalog_record_tag_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Catalog_Record',
        ),
    ]
